# Generated by Django 4.0.5 on 2022-12-05 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idioma_descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('pais_de_origem', models.CharField(max_length=255)),
                ('tempo_no_brasil', models.CharField(max_length=255)),
                ('esta_empregado', models.CharField(max_length=255)),
                ('dificuldade_imigrante', models.CharField(max_length=255)),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.idiomas')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_titulo', models.CharField(max_length=100)),
                ('post_descricao', models.CharField(max_length=255)),
                ('post_conteudo', models.TextField()),
                ('imagem', models.URLField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.idiomas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
