# Generated by Django 4.0.5 on 2022-11-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreIdiomas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idiomas_descri', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CorePerguntas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('perguntas_descri', models.CharField(max_length=255)),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreidiomas')),
            ],
        ),
        migrations.CreateModel(
            name='CoreRespostas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('pais_de_origem', models.CharField(max_length=255)),
                ('tempo_no_brasil', models.CharField(max_length=255)),
                ('esta_empregado', models.CharField(max_length=255)),
                ('dificuldade_imigrante', models.CharField(max_length=255)),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreidiomas')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreperguntas')),
            ],
        ),
        migrations.CreateModel(
            name='CorePosts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_titulo', models.CharField(max_length=100)),
                ('post_descricao', models.CharField(max_length=255)),
                ('post_conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreidiomas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
