# Generated by Django 4.0.5 on 2022-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_titulo', models.CharField(max_length=100)),
                ('post_descricao', models.CharField(max_length=255)),
                ('post_conteudo', models.CharField(max_length=255)),
            ],
        ),
    ]
