# Generated by Django 4.0.5 on 2022-11-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas_descri', models.CharField(max_length=255)),
                ('respostas', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.respostas')),
            ],
        ),
    ]
