# Generated by Django 4.0.5 on 2022-11-08 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_perguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='usuario',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_conteudo',
            field=models.TextField(max_length=255),
        ),
    ]
