# Generated by Django 4.0.5 on 2022-11-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_posts_usuario_posts_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntas',
            name='respostas',
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perguntas'),
        ),
    ]
